version: "3.9"

services:
  sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /socialnetwork_api
    image: danielshtel/sqlite
    env_file:
      - .env
    entrypoint: ["python" , "database.py"]

    volumes:
      - .:/socialnetwork_api
    depends_on:
      - instafood_api

  instafood_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: danielshtel/instafood
    volumes:
      - .:/socialnetwork_api
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}