version: "3.9"
volumes:
  data:

services:
  sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /socialnetwork_api
    image: danielshtel/sqlite
    env_file:
      - .env
    entrypoint: ["python" , "database.py"]

    volumes:
      - data:/socialnetwork_api
    depends_on:
      - instafood_api

  instafood_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: danielshtel/instafood
    volumes:
      - data:/socialnetwork_api
    env_file:
      - .env
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}